# -*- coding: utf-8 -*-
"""Spotify_Trend_Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hmUuOyXKPluLlQZjC02Pp9vSoF6CIt2O

# 🎧 Spotify Listening Trend Analyzer
Analyze top tracks of an artist using Spotify API and Spotipy.
"""

# Install spotipy (only needed once)
!pip install spotipy

# Import libraries
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Fill in your own Spotify Developer credentials
client_id = '2d246175ec1a4a078dad67110ef070c4'
client_secret = 'f4d112629e444e2d8d18cbf18e84ae61'

# Authenticate
auth_manager = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
sp = spotipy.Spotify(auth_manager=auth_manager)

# Convert to DataFrame
tracks = [{
    'Track': track['name'],
    'Popularity': track['popularity'],
    'Album': track['album']['name']
} for track in results ['tracks']]

df = pd.DataFrame(tracks)
df

# Example: Top tracks by artist (The Weeknd)
artist_uri = 'spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ'
results = sp.artist_top_tracks(artist_uri)

from spotipy.oauth2 import SpotifyClientCredentials
import spotipy

# Replace with your actual keys
client_id = '2d246175ec1a4a078dad67110ef070c4'
client_secret = 'f4d112629e444e2d8d18cbf18e84ae61'

auth_manager = SpotifyClientCredentials(client_id=client_id, client_secret=client_secret)
sp = spotipy.Spotify(auth_manager=auth_manager)

# Example: Get top tracks of The Weeknd
artist_uri = 'spotify:artist:1Xyo4u8uXC1ZmMpatF05PJ'
results = sp.artist_top_tracks(artist_uri)

import matplotlib.pyplot as plt
import seaborn as sns

# Sort and get top 10 tracks
top_n = 10
top_tracks = df.sort_values(by='Popularity', ascending=False).head(top_n)

# Plot
plt.figure(figsize=(10,6))
sns.barplot(x='Popularity', y='Track', data=top_tracks, palette='viridis')
plt.title('Top 10 Tracks by Popularity')
plt.xlabel('Popularity')
plt.ylabel('Track')
plt.tight_layout()
plt.show()